---
search_terms:
  - Record store day
  - RSD16
  - RSD20126
  - RSD
  - ElectricLady
  - Electric lady
  - post rock
  - riot grrrl
  - riot-grrrl
  - prog rock
feeds:
  - http://www.nme.com/rss/reviews
  - http://www.nme.com/rss/news
  - http://www.rollingstone.com/music/songreviews.rss
  - http://www.rollingstone.com/music/albumreviews.rss
  - http://www.rollingstone.com/culture.rss
  - http://www.rollingstone.com/music.rss
  - http://www.bbc.co.uk/feeds/rss/music/latest_releases.xml
  - http://www.bbc.co.uk/music/genres/classicpopandrock/reviews.rss
  - http://www.bbc.co.uk/music/genres/jazzandblues/reviews.rss
  - http://pitchfork.com/rss/news/
  - http://pitchfork.com/rss/reviews/albums/
  - http://pitchfork.com/rss/reviews/tracks/
  - http://pitchfork.com/rss/features/
