version: '2'
services:
  summariser: &ourservice
    build: .
    links:
      - redis
    depends_on:
      - redis
    working_dir: /usr/src/app
    command: bundle exec ruby summariser.rb
    volumes:
      - ./config:/config
    environment:
      REDIS_HOST: 'redis'
      DOCKER_MODE: '1'
      FLICKR_KEY:
      FLICKR_SECRET:

  markov:
    <<: *ourservice
    command: bundle exec ruby markov.rb

  watcher:
    <<: *ourservice
    command: bundle exec ruby watcher.rb

  follower:
    <<: *ourservice
    command: bundle exec ruby follower.rb

  imager:
    <<: *ourservice
    command: bundle exec ruby imager.rb

  frontend:
    <<: *ourservice
    working_dir: /usr/src/app/text
    command: thin start
    ports:
      - "3000"

  redis:
    image: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379"
