source 'https://rubygems.org'

gem 'chatterbot'
gem 'whatlanguage', github: 'peterc/whatlanguage'
#gem 'marky_markov', github: 'zolrath/marky_markov'
gem 'marky_markov'
gem 'ots', github: 'deepfryed/ots'
gem 'simple-rss'
gem 'redis'
gem 'sinatra'
gem 'rack'
gem 'unicorn'
gem 'thin'
gem 'flickraw'
gem 'httparty'
